echo "---------------------------------"
echo "Tugas 1 SISOP Kelas A"
echo "---------------------------------"
echo "Nama: Ellexia Leonie Gunawan"
echo "NPM: 21083010027"
echo "---------------------------------"
echo "notes: "
echo "---------------------------------"
echo "Halo dunia!"
echo "Ini adalah skrip Bash pertamaku di Linux"
